config/routes.rb
Rails.application.routes.draw do
  #resources :comments
  #resources :publications
  resources :publications do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  devise_for :users
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy
  belongs_to :user

  #validations
  validates :title, presence: true, length: {maximum: 70}
  validates :title, presence: true, length: {maximum: 500}
  #validates :category, presence: true
  #por qué la linea anterior me daña el código
  validates :status, presence: true

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :set_categories, only: %i[new create edit update]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    #This ask if publications has comments and if publication does not have we return nil
    @comments = @publication.comments.any? ? @publication.comments : nil
    @new_comment = @publication.comments.build
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    #array for tag select
    
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    parametros = publication_params
    parametros["user_id"] = current_user.id
    @publication = Publication.new(parametros)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy!

    respond_to do |format|
      format.html { redirect_to publications_path, status: :see_other, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    def set_categories
      @categories = Category.all
      @options = []
      @categories.each do |category|
        array =  [category.name, category.id]
        @options << array 
        end
        puts @options
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :description, :category_id, :status, :user_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.select(:category_id, options_for_select(@options))%>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p>
    <strong>Title:</strong>
    <%= publication.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= publication.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= publication.category.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= publication.status %>
  </p>

  <p>
    <strong>User:</strong>
    <%= publication.user.name %>
  </p>

</div>

app/views/publications/edit.html.erb
<% content_for :title, "Editing publication" %>

<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Publications" %>

<h1>Publications</h1>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Show this publication", publication %>
    </p>
  <% end %>
</div>

<%= link_to "New publication", new_publication_path %>

app/views/publications/new.html.erb
<% content_for :title, "New publication" %>

<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publication %>

<div>
  <h3>Comments</h3>
  <% if !@comments.nil? %>
    <% puts "SI HAY COMENTARIOS"%>
    <% puts @comments.inspect %>
    <ul>
      <% @comments.each do |comment| %>
        <li>
          <%usuario = comment.user%>
          <% if comment.user %>
          <%puts "ESTO ES Comment #{comment.inspect}"%>
            <p><%= comment.description %> - <small>by <%= usuario.name %></small></p>
            <% if current_user == comment.user || current_user.role == "admin" %>
              <%= button_to "Edit", edit_publication_comment_path(@publication, comment), method: :get %> 
              <%= button_to "Delete", publication_comment_path(@publication, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No comments yet.</p>
  <% end %>
</div>

<h4>Add a Comment</h4>
<%= form_with model: [@publication, @new_comment], local: true do |form| %>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description, rows: 3 %>
  </div>
  <div>
    <%= form.submit "Post Comment" %>
  </div>
<% end %>

<div>
  <% if @publication.user.name == current_user.name || current_user.role == "admin"%>
    <%= link_to "Edit this publication", edit_publication_path(@publication) %> |
    <%= button_to "Destroy this publication", @publication, method: :delete %>
  <% end%>
    <%= link_to "Back to publications", publications_path %>
</div>